openapi: 3.0.0
info:
  title: PhysicalUEProxy API
  description: SBI for UE physical proxy
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

paths:
  /device-id:
    get:
      summary: get the device imsi
      description: |
        Get the imsi of the controlled device
      operationId: get_device_imsi
      responses:
        "200":
          description: The device imsi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Supi'
        default:
          description: Generic-error
      x-openapi-router-controller: server.controllers.default_controller
  /gnb-connection-state:
    get:
      summary: get the UE connection state with gNB
      description: |
        get the UE connection state with gNB
      operationId: get_gnb_connection_state
      responses:
        "200":
          description: The UE connection state with gNB
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GnbConnectionState'
        default:
          description: Generic-error
      x-openapi-router-controller: server.controllers.default_controller
  /pdu-session:
    get:
      summary: get the established PDU sessions list
      description: |
        Get the established PDU sessions list.
      operationId: get_pdu_sessions
      responses:
        "200":
          description: The list of established PDU session
          content:
            application/json:
              schema:
                minItems: 0
                type: array
                items:
                  $ref: '#/components/schemas/EstablishedSession'
                x-content-type: application/json
        default:
          description: Generic-error
      x-openapi-router-controller: server.controllers.default_controller
    post:
      summary: create a new PDU Session
      description: |
        Create a new PDU Session for the UE.
      operationId: create_pdu_session
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelectedSession'
        required: true
      responses:
        "200":
          description: Pdu Session sucessfully established
        default:
          description: Generic-error
      x-openapi-router-controller: server.controllers.default_controller
    delete:
      summary: Delete a specific PDU Session
      description: |
        Delete a PDU Session previusly created for the UE.
      operationId: delete_pdu_session
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelectedPDU'
        required: true
      responses:
        "200":
          description: Pdu Session sucessfully deleted
        default:
          description: Generic-error
      x-openapi-router-controller: server.controllers.default_controller
components:
  schemas:
    Supi:
      pattern: "^(imsi-[0-9]{5,15}|nai-.+|gci-.+|gli-.+|.+)$"
      type: string
    EstablishedSession:
      required:
      - dnn
      - ipAddress
      - sst
      type: object
      properties:
        id:
          type: integer
        sst:
          maximum: 255
          minimum: 0
          type: integer
        sd:
          pattern: "^[A-Fa-f0-9]{6}$"
          type: string
        dnn:
          type: string
        pduSessionType:
          $ref: '#/components/schemas/PduSessionType'
        ipAddress:
          $ref: '#/components/schemas/IpAddress'
        emergency:
          type: boolean
      example:
        sd: sd
        sst: 153
        dnn: dnn
        ipAddress:
          ipv6Addr: ""
          ipv4Addr: ipv4Addr
          ipv6Prefix: ""
        emergency: true
        pduSessionTypes: ""
        id: 0
    SelectedSession:
      required:
      - sst
      type: object
      properties:
        sst:
          maximum: 255
          minimum: 0
          type: integer
        sd:
          pattern: "^[A-Fa-f0-9]{6}$"
          type: string
        dnn:
          type: string
        pduSessionType:
          $ref: '#/components/schemas/PduSessionType'
    PduSessionType:
      anyOf:
      - type: string
        enum:
        - IPV4
        - IPV6
        - IPV4V6
        - UNSTRUCTURED
        - ETHERNET
    SelectedPDU:
      required:
      - pdu_id
      type: object
      properties:
        pdu_id:
          maximum: 255
          minimum: 0
          type: integer
    CellConnectionStatus:
      anyOf:
      - type: string
        enum:
        - CM-CONNECTED
        - CM-IDLE
    GnbConnectionState:
      required:
      - status
      type: object
      properties:
        status:
          $ref: '#/components/schemas/CellConnectionStatus'
        camped-cell:
          type: string
      example:
        camped-cell: camped-cell
        status: ""
    IpAddress:
      type: object
      properties:
        ipv4Addr:
          $ref: '#/components/schemas/Ipv4Addr'
        ipv6Addr:
          $ref: '#/components/schemas/Ipv6Addr'
        ipv6Prefix:
          $ref: '#/components/schemas/Ipv6Prefix'
      example:
        ipv6Addr: ""
        ipv4Addr: ipv4Addr
        ipv6Prefix: ""
      oneOf:
      - required:
        - ipv4Addr
      - required:
        - ipv6Addr
      - required:
        - ipv6Prefix
    Ipv4Addr:
      pattern: "^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$"
      type: string
    Ipv6Addr:
      type: string
      allOf:
      - pattern: "^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))$"
      - pattern: "^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))$"
    Ipv6Prefix:
      type: string
      allOf:
      - pattern: "^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))(\\\
          /(([0-9])|([0-9]{2})|(1[0-1][0-9])|(12[0-8])))$"
      - pattern: "^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))(\\\
          /.+)$"

