# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server.models.base_model_ import Model
from server.models.ip_address import IpAddress  # noqa: F401,E501
from server import util


class SessionInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, ip_address: IpAddress=None, emergency: bool=None):  # noqa: E501
        """SessionInfo - a model defined in Swagger

        :param id: The id of this SessionInfo.  # noqa: E501
        :type id: int
        :param ip_address: The ip_address of this SessionInfo.  # noqa: E501
        :type ip_address: IpAddress
        :param emergency: The emergency of this SessionInfo.  # noqa: E501
        :type emergency: bool
        """
        self.swagger_types = {
            'id': int,
            'ip_address': IpAddress,
            'emergency': bool
        }

        self.attribute_map = {
            'id': 'id',
            'ip_address': 'ipAddress',
            'emergency': 'emergency'
        }
        self._id = id
        self._ip_address = ip_address
        self._emergency = emergency

    @classmethod
    def from_dict(cls, dikt) -> 'SessionInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SessionInfo of this SessionInfo.  # noqa: E501
        :rtype: SessionInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this SessionInfo.


        :return: The id of this SessionInfo.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this SessionInfo.


        :param id: The id of this SessionInfo.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def ip_address(self) -> IpAddress:
        """Gets the ip_address of this SessionInfo.


        :return: The ip_address of this SessionInfo.
        :rtype: IpAddress
        """
        return self._ip_address

    @ip_address.setter
    def ip_address(self, ip_address: IpAddress):
        """Sets the ip_address of this SessionInfo.


        :param ip_address: The ip_address of this SessionInfo.
        :type ip_address: IpAddress
        """
        if ip_address is None:
            raise ValueError("Invalid value for `ip_address`, must not be `None`")  # noqa: E501

        self._ip_address = ip_address

    @property
    def emergency(self) -> bool:
        """Gets the emergency of this SessionInfo.


        :return: The emergency of this SessionInfo.
        :rtype: bool
        """
        return self._emergency

    @emergency.setter
    def emergency(self, emergency: bool):
        """Sets the emergency of this SessionInfo.


        :param emergency: The emergency of this SessionInfo.
        :type emergency: bool
        """

        self._emergency = emergency
